[package]
name = "libfdk-aac-sys"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Sedlak <daniel@sedlak.dev>"]
license = "MIT"
description = """
Exported bindings to the libfdk-aac for AAC encoding and decoding.
"""

[build-dependencies]
bindgen = "0.69.4"
